% trance on new subjects, processed in 09-09-2019
patlist = {
    %'N'                              'Adm diag' 'CRS Diag' 'PET' 'tennis' 'TBI?'  'Age'  'male'   'days   onset' 'Outcome' 'CRS-R score'    
    'Subject_001_EO'              NaN		1		NaN		NaN		NaN		36		0		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_001_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_001_VRH'             NaN		3		NaN		NaN		NaN		36		0		NaN		NaN		NaN     NaN     NaN     NaN
   'Subject_002_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_002_Hyp'             NaN		2		NaN		NaN		NaN		36		0		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_002_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_003_EO'              NaN		1		NaN		NaN		NaN		36		0		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_003_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_003_VRH'             NaN		3		NaN		NaN		NaN		32		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_004_EO'              NaN		1		NaN		NaN		NaN		48		0		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_004_Hyp'             NaN		2		NaN		NaN		NaN		37		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_004_VRH'             NaN		3		NaN		NaN		NaN		36		0		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_005_EO'              NaN		1		NaN		NaN		NaN		36		0		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_005_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_005_VRH'             NaN		3		NaN		NaN		NaN		32		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_006_EO'              NaN		1		NaN		NaN		NaN		48		0		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_006_Hyp'             NaN		2		NaN		NaN		NaN		37		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_006_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_007_EO'              NaN		1		NaN		NaN		NaN		32		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_007_Hyp'             NaN		2		NaN		NaN		NaN		48		0		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_007_VRH'             NaN		3		NaN		NaN		NaN		37		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_008_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_008_Hyp'             NaN		2		NaN		NaN		NaN		32		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_008_VRH'             NaN		3		NaN		NaN		NaN		48		0		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_009_EO'              NaN		1		NaN		NaN		NaN		32		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_009_Hyp'             NaN		2		NaN		NaN		NaN		48		0		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_009_VRH'             NaN		3		NaN		NaN		NaN		37		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_010_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_010_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_010_VRH'             NaN		3		NaN		NaN		NaN		36		0		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_011_EO'              NaN		1		NaN		NaN		NaN		36		0		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_011_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_011_VRH'             NaN		3		NaN		NaN		NaN		32		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_012_EO'              NaN		1		NaN		NaN		NaN		48		0		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_012_Hyp'             NaN		2		NaN		NaN		NaN		37		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_012_VRH'             NaN		3		NaN		NaN		NaN		36		0		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_013_EO'              NaN		1		NaN		NaN		NaN		36		0		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_013_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_013_VRH'             NaN		3		NaN		NaN		NaN		32		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_014_EO'              NaN		1		NaN		NaN		NaN		48		0		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_014_Hyp'             NaN		2		NaN		NaN		NaN		37		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_014_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_015_EO'              NaN		1		NaN		NaN		NaN		32		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_015_Hyp'             NaN		2		NaN		NaN		NaN		48		0		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_015_VRH'             NaN		3		NaN		NaN		NaN		37		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_016_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_016_Hyp'             NaN		2		NaN		NaN		NaN		32		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_016_VRH'             NaN		3		NaN		NaN		NaN		48		0		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_017_EO'              NaN		1		NaN		NaN		NaN		32		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_017_Hyp'             NaN		2		NaN		NaN		NaN		48		0		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_017_VRH'             NaN		3		NaN		NaN		NaN		37		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_018_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_018_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_018_VRH'             NaN		3		NaN		NaN		NaN		36		0		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_019_EO'              NaN		1		NaN		NaN		NaN		36		0		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_019_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_019_VRH'             NaN		3		NaN		NaN		NaN		32		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_020_EO'              NaN		1		NaN		NaN		NaN		48		0		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_020_Hyp'             NaN		2		NaN		NaN		NaN		37		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_020_VRH'             NaN		3		NaN		NaN		NaN		36		0		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_021_EO'              NaN		1		NaN		NaN		NaN		36		0		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_021_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_021_VRH'             NaN		3		NaN		NaN		NaN		32		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_022_EO'              NaN		1		NaN		NaN		NaN		48		0		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_022_Hyp'             NaN		2		NaN		NaN		NaN		37		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_022_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_023_EO'              NaN		1		NaN		NaN		NaN		32		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_023_Hyp'             NaN		2		NaN		NaN		NaN		48		0		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_023_VRH'             NaN		3		NaN		NaN		NaN		37		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_024_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_024_Hyp'             NaN		2		NaN		NaN		NaN		32		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_024_VRH'             NaN		3		NaN		NaN		NaN		48		0		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_025_EO'              NaN		1		NaN		NaN		NaN		32		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_025_Hyp'             NaN		2		NaN		NaN		NaN		48		0		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_025_VRH'             NaN		3		NaN		NaN		NaN		37		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_026_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_026_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_026_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_027_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_027_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_027_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_028_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_028_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_028_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_029_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_029_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_029_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_030_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_030_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_030_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_031_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_031_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_031_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_032_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_032_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_032_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_033_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_033_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_033_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_034_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_034_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_034_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_035_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_035_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
   'Subject_035_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_036_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_036_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_036_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_037_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_037_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_037_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_038_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_038_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_038_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_039_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_039_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_039_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_040_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_040_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_040_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_041_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_041_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_041_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_042_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_042_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_042_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_043_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_043_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_043_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_044_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_044_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_044_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_045_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_045_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_045_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_046_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_046_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_046_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_047_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_047_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_047_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_048_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_048_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_048_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_049_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_049_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_049_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_050_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_050_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_050_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_051_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_051_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_051_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_052_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_052_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_052_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_053_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_053_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_053_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_054_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_054_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_054_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_055_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_055_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_055_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_056_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_056_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_056_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_057_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_057_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_057_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_058_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_058_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_058_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_059_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_059_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_059_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_060_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_060_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_060_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_061_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_061_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_061_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_062_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_062_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_062_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_063_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_063_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_063_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_064_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_064_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_064_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_065_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_065_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_065_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_066_EO'              NaN		1		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_066_Hyp'             NaN		2		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    'Subject_066_VRH'             NaN		3		NaN		NaN		NaN		62		1		NaN		NaN		NaN     NaN     NaN     NaN
    
    };

ctrllist = {
           };

%%% (changed by raja) allsubj = cat(1,patlist,ctrllist);
allpat = patlist;
allsubj = cat(1,allpat,ctrllist); %%% (changed by raja)
